export default {
  object_kind: 'note',
  user: {
    name: 'tang',
    username: 'tang',
    avatar_url:
      'http://git.mistong.com/uploads/user/avatar/4/4e97a4977e71a729cbe3a9aa082b3ee.jpg',
  },
  project_id: 2810,
  project: {
    name: 'code-review',
    description: '',
    web_url: 'http://git.mistong.com/jingweirong/code-review',
    avatar_url: null,
    git_ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    namespace: 'jingweirong',
    visibility_level: 20,
    path_with_namespace: 'jingweirong/code-review',
    default_branch: 'master',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    http_url: 'http://git.mistong.com/jingweirong/code-review.git',
  },
  object_attributes: {
    id: 84073,
    note: '评论 @tang @jingweirong',
    noteable_type: 'MergeRequest',
    author_id: 4,
    created_at: '2022-01-19 03:06:13 UTC',
    updated_at: '2022-01-19 03:06:13 UTC',
    project_id: 2810,
    attachment: null,
    line_code: '8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d_4_4',
    commit_id: '',
    noteable_id: 33701,
    system: false,
    st_diff: null,
    updated_by_id: null,
    type: 'DiffNote',
    position: {
      old_path: 'README.md',
      new_path: 'README.md',
      old_line: null,
      new_line: 4,
      base_sha: 'adf4ea71d6996cf1e51b88bced9f501aa25358df',
      start_sha: 'adf4ea71d6996cf1e51b88bced9f501aa25358df',
      head_sha: '840a5c1f2a58e83f29a168d29ab59b0f0ff45e05',
    },
    original_position: {
      old_path: 'README.md',
      new_path: 'README.md',
      old_line: null,
      new_line: 4,
      base_sha: 'adf4ea71d6996cf1e51b88bced9f501aa25358df',
      start_sha: 'adf4ea71d6996cf1e51b88bced9f501aa25358df',
      head_sha: '840a5c1f2a58e83f29a168d29ab59b0f0ff45e05',
    },
    resolved_at: null,
    resolved_by_id: null,
    discussion_id: '4ea4a9bb6b7b1dce628e70623c99be817ac88e8e',
    original_discussion_id: '4ea4a9bb6b7b1dce628e70623c99be817ac88e8e',
    url: 'http://git.mistong.com/jingweirong/code-review/merge_requests/2#note_84073',
  },
  repository: {
    name: 'code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    description: '',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
  },
  merge_request: {
    id: 33701,
    target_branch: 'trunk',
    source_branch: 'master',
    source_project_id: 2810,
    author_id: 4,
    assignee_id: 251,
    title: 'title',
    created_at: '2022-01-18 02:21:35 UTC',
    updated_at: '2022-01-19 03:06:13 UTC',
    milestone_id: null,
    state: 'opened',
    merge_status: 'can_be_merged',
    target_project_id: 2810,
    iid: 2,
    description: 'Description',
    position: 0,
    locked_at: null,
    updated_by_id: null,
    merge_error: null,
    merge_params: { force_remove_source_branch: null },
    merge_when_build_succeeds: false,
    merge_user_id: null,
    merge_commit_sha: null,
    deleted_at: null,
    in_progress_merge_commit_sha: null,
    lock_version: 0,
    source: {
      name: 'code-review',
      description: '',
      web_url: 'http://git.mistong.com/jingweirong/code-review',
      avatar_url: null,
      git_ssh_url:
        'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
      namespace: 'jingweirong',
      visibility_level: 20,
      path_with_namespace: 'jingweirong/code-review',
      default_branch: 'master',
      homepage: 'http://git.mistong.com/jingweirong/code-review',
      url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    },
    target: {
      name: 'code-review',
      description: '',
      web_url: 'http://git.mistong.com/jingweirong/code-review',
      avatar_url: null,
      git_ssh_url:
        'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
      namespace: 'jingweirong',
      visibility_level: 20,
      path_with_namespace: 'jingweirong/code-review',
      default_branch: 'master',
      homepage: 'http://git.mistong.com/jingweirong/code-review',
      url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    },
    last_commit: {
      id: '840a5c1f2a58e83f29a168d29ab59b0f0ff45e05',
      message: 'Update README.md',
      timestamp: '2022-01-18T10:14:27+08:00',
      url: 'http://git.mistong.com/jingweirong/code-review/commit/840a5c1f2a58e83f29a168d29ab59b0f0ff45e05',
      author: { name: 'jingweirong', email: 'jingweirong@mistong.com' },
    },
    work_in_progress: false,
  },
};
