export default {
  object_kind: 'issue',
  user: {
    name: 'jingweirong',
    username: 'jingweirong',
    avatar_url: 'http://git.mistong.com/uploads/user/avatar/251/avatar.png',
  },
  project: {
    name: 'code-review',
    description: '',
    web_url: 'http://git.mistong.com/jingweirong/code-review',
    avatar_url: null,
    git_ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    namespace: 'jingweirong',
    visibility_level: 20,
    path_with_namespace: 'jingweirong/code-review',
    default_branch: 'master',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    http_url: 'http://git.mistong.com/jingweirong/code-review.git',
  },
  object_attributes: {
    id: 166,
    title: '条件issue标题',
    assignee_id: 402,
    author_id: 251,
    project_id: 2810,
    created_at: '2022-02-08 10:43:30 +0800',
    updated_at: '2022-02-08 10:43:30 +0800',
    position: 0,
    branch_name: null,
    description: '条件issue描述',
    milestone_id: null,
    state: 'opened',
    iid: 2,
    updated_by_id: null,
    confidential: true,
    deleted_at: null,
    due_date: null,
    moved_to_id: null,
    lock_version: 0,
    url: 'http://git.mistong.com/jingweirong/code-review/issues/2',
    action: 'open',
  },
  repository: {
    name: 'code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    description: '',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
  },
  assignee: {
    name: '吴>达建',
    username: 'wudajian',
    avatar_url:
      'http://www.gravatar.com/avatar/75730c2b8be0cb5642832bc4807acd11?s=80&d=identicon',
  },
};
