export default {
  object_kind: 'issue',
  user: {
    name: 'jingweirong',
    username: 'jingweirong',
    avatar_url: 'http://git.mistong.com/uploads/user/avatar/251/avatar.png',
  },
  project: {
    name: 'code-review',
    description: '',
    web_url: 'http://git.mistong.com/jingweirong/code-review',
    avatar_url: null,
    git_ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    namespace: 'jingweirong',
    visibility_level: 20,
    path_with_namespace: 'jingweirong/code-review',
    default_branch: 'master',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    http_url: 'http://git.mistong.com/jingweirong/code-review.git',
  },
  object_attributes: {
    id: 165,
    title: '第一个issue',
    assignee_id: 4,
    author_id: 251,
    project_id: 2810,
    created_at: '2022-02-08 10:34:27 +0800',
    updated_at: '2022-02-08 10:34:27 +0800',
    position: 0,
    branch_name: null,
    description: 'issue的描述',
    milestone_id: null,
    state: 'opened',
    iid: 1,
    updated_by_id: null,
    confidential: false,
    deleted_at: null,
    due_date: null,
    moved_to_id: null,
    lock_version: 0,
    url: 'http://git.mistong.com/jingweirong/code-review/issues/1',
    action: 'open',
  },
  repository: {
    name: 'code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    description: '',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
  },
  assignee: {
    name: 'tang',
    username: 'tang',
    avatar_url:
      'http://git.mistong.com/uploads/user/avatar/4/4e97a4977e71a729cbe3a9aa082b3ee.jpg',
  },
};
