export default {
  object_kind: 'merge_request',
  user: {
    name: 'jingweirong',
    username: 'jingweirong',
    avatar_url: 'http://git.mistong.com/uploads/user/avatar/251/avatar.png',
  },
  project: {
    name: 'bend-homework',
    description: 'B 端作业体系（PC—新），owner 达建，长老',
    web_url: 'http://git.mistong.com/frontend-to-b/bend-homework',
    avatar_url: null,
    git_ssh_url:
      'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
    git_http_url: 'http://git.mistong.com/frontend-to-b/bend-homework.git',
    namespace: 'frontend-to-b',
    visibility_level: 20,
    path_with_namespace: 'frontend-to-b/bend-homework',
    default_branch: 'master',
    homepage: 'http://git.mistong.com/frontend-to-b/bend-homework',
    url: 'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
    ssh_url: 'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
    http_url: 'http://git.mistong.com/frontend-to-b/bend-homework.git',
  },
  object_attributes: {
    id: 33946,
    target_branch: 'trunk',
    source_branch: 'codereview_test',
    source_project_id: 2378,
    author_id: 251,
    assignee_id: 380,
    title: '测试代码，无需合并',
    created_at: '2022-01-24 15:28:16 +0800',
    updated_at: '2022-01-24 15:30:42 +0800',
    milestone_id: null,
    state: 'closed',
    merge_status: 'can_be_merged',
    target_project_id: 2378,
    iid: 303,
    description: 'MR的描述',
    position: 0,
    locked_at: null,
    updated_by_id: 251,
    merge_error: null,
    merge_params: { force_remove_source_branch: '0' },
    merge_when_build_succeeds: false,
    merge_user_id: null,
    merge_commit_sha: null,
    deleted_at: null,
    in_progress_merge_commit_sha: null,
    lock_version: 0,
    source: {
      name: 'bend-homework',
      description: 'B 端作业体系（PC—新），owner 达建>，长老',
      web_url: 'http://git.mistong.com/frontend-to-b/bend-homework',
      avatar_url: null,
      git_ssh_url:
        'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
      git_http_url: 'http://git.mistong.com/frontend-to-b/bend-homework.git',
      namespace: 'frontend-to-b',
      visibility_level: 20,
      path_with_namespace: 'frontend-to-b/bend-homework',
      default_branch: 'master',
      homepage: 'http://git.mistong.com/frontend-to-b/bend-homework',
      url: 'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
      ssh_url:
        'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
      http_url: 'http://git.mistong.com/frontend-to-b/bend-homework.git',
    },
    target: {
      name: 'bend-homework',
      description: 'B 端作业体系（PC—新），owner 达建，长老',
      web_url: 'http://git.mistong.com/frontend-to-b/bend-homework',
      avatar_url: null,
      git_ssh_url:
        'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
      git_http_url: 'http://git.mistong.com/frontend-to-b/bend-homework.git',
      namespace: 'frontend-to-b',
      visibility_level: 20,
      path_with_namespace: 'frontend-to-b/bend-homework',
      default_branch: 'master',
      homepage: 'http://git.mistong.com/frontend-to-b/bend-homework',
      url: 'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
      ssh_url:
        'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
      http_url: 'http://git.mistong.com/frontend-to-b/bend-homework.git',
    },
    last_commit: {
      id: '6f10c1aeb9d7634a30ee353d54790ccca67488ab',
      message: 'Update README.md',
      timestamp: '2022-01-24T15:04:17+08:00',
      url: 'http://git.mistong.com/frontend-to-b/bend-homework/commit/6f10c1aeb9d7634a30ee353d54790ccca67488ab',
      author: { name: 'jingweirong', email: 'jingweirong@mistong.com' },
    },
    work_in_progress: false,
    url: 'http://git.mistong.com/frontend-to-b/bend-homework/merge_requests/303',
    action: 'update',
  },
  repository: {
    name: 'bend-homework',
    url: 'ssh://git@git.mistong.com:10022/frontend-to-b/bend-homework.git',
    description: 'B 端作业体系（PC—新），owner 达建，长老',
    homepage: 'http://git.mistong.com/frontend-to-b/bend-homework',
  },
  assignee: {
    name: '娄金亮',
    username: 'loujinliang',
    avatar_url: 'http://git.mistong.com/uploads/user/avatar/380/avatar.png',
  },
};
