export default {
  object_kind: 'merge_request',
  user: {
    name: 'duting',
    username: 'duting',
    avatar_url:
      'http://www.gravatar.com/avatar/be0433ba7a4c6508dc659306cb545bf4?s=80&d=identicon',
  },
  project: {
    name: 'live2020',
    description: '',
    web_url: 'http://git.mistong.com/web/live2020',
    avatar_url: null,
    git_ssh_url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
    git_http_url: 'http://git.mistong.com/web/live2020.git',
    namespace: 'web',
    visibility_level: 0,
    path_with_namespace: 'web/live2020',
    default_branch: 'master',
    homepage: 'http://git.mistong.com/web/live2020',
    url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
    ssh_url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
    http_url: 'http://git.mistong.com/web/live2020.git',
  },
  object_attributes: {
    id: 33956,
    target_branch: 'release_pre',
    source_branch: 'feat_ewtLogoReplace',
    source_project_id: 2208,
    author_id: 251,
    assignee_id: 441,
    title: 'feat: change ewtlogo to Mst happy new year',
    created_at: '2022-01-24 09:12:37 UTC',
    updated_at: '2022-01-24 09:16:47 UTC',
    milestone_id: null,
    state: 'merged',
    merge_status: 'can_be_merged',
    target_project_id: 2208,
    iid: 3,
    description: '大年夜直播，logo临时替换一下',
    position: 0,
    locked_at: null,
    updated_by_id: null,
    merge_error: null,
    merge_params: { force_remove_source_branch: '0' },
    merge_when_build_succeeds: false,
    merge_user_id: null,
    merge_commit_sha: '37a1c98fd7193cdbbdd104dcd9f365954fcbc403',
    deleted_at: null,
    in_progress_merge_commit_sha: null,
    lock_version: 0,
    source: {
      name: 'live2020',
      description: '',
      web_url: 'http://git.mistong.com/web/live2020',
      avatar_url: null,
      git_ssh_url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
      git_http_url: 'http://git.mistong.com/web/live2020.git',
      namespace: 'web',
      visibility_level: 0,
      path_with_namespace: 'web/live2020',
      default_branch: 'master',
      homepage: 'http://git.mistong.com/web/live2020',
      url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
      ssh_url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
      http_url: 'http://git.mistong.com/web/live2020.git',
    },
    target: {
      name: 'live2020',
      description: '',
      web_url: 'http://git.mistong.com/web/live2020',
      avatar_url: null,
      git_ssh_url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
      git_http_url: 'http://git.mistong.com/web/live2020.git',
      namespace: 'web',
      visibility_level: 0,
      path_with_namespace: 'web/live2020',
      default_branch: 'master',
      homepage: 'http://git.mistong.com/web/live2020',
      url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
      ssh_url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
      http_url: 'http://git.mistong.com/web/live2020.git',
    },
    last_commit: {
      id: '658e8c83dde509d10bc2ddf81ba0f9078f33b16c',
      message: 'feat: change ewtlogo to Mst happy new year\n',
      timestamp: '2022-01-24T17:04:22+08:00',
      url: 'http://git.mistong.com/web/live2020/commit/658e8c83dde509d10bc2ddf81ba0f9078f33b16c',
      author: { name: 'yukap', email: 'jingweirong@mistong.com' },
    },
    work_in_progress: false,
    url: 'http://git.mistong.com/web/live2020/merge_requests/3',
    action: 'merge',
  },
  repository: {
    name: 'live2020',
    url: 'ssh://git@git.mistong.com:10022/web/live2020.git',
    description: '',
    homepage: 'http://git.mistong.com/web/live2020',
  },
  assignee: {
    name: 'duting',
    username: 'duting',
    avatar_url:
      'http://www.gravatar.com/avatar/be0433ba7a4c6508dc659306cb545bf4?s=80&d=identicon',
  },
};
