export default {
  object_kind: 'merge_request',
  user: {
    name: 'tang',
    username: 'tang',
    avatar_url:
      'http://git.mistong.com/uploads/user/avatar/4/4e97a4977e71a729cbe3a9aa082b3ee.jpg',
  },
  project: {
    name: 'code-review',
    description: '',
    web_url: 'http://git.mistong.com/jingweirong/code-review',
    avatar_url: null,
    git_ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    namespace: 'jingweirong',
    visibility_level: 20,
    path_with_namespace: 'jingweirong/code-review',
    default_branch: 'master',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    http_url: 'http://git.mistong.com/jingweirong/code-review.git',
  },
  object_attributes: {
    id: 33701,
    target_branch: 'trunk',
    source_branch: 'master',
    source_project_id: 2810,
    author_id: 4,
    assignee_id: 251,
    title: 'title',
    created_at: '2022-01-18 10:21:35 +0800',
    updated_at: '2022-01-18 10:21:35 +0800',
    milestone_id: null,
    state: 'opened',
    merge_status: 'unchecked',
    target_project_id: 2810,
    iid: 2,
    description: 'Description',
    position: 0,
    locked_at: null,
    updated_by_id: null,
    merge_error: null,
    merge_params: { force_remove_source_branch: null },
    merge_when_build_succeeds: false,
    merge_user_id: null,
    merge_commit_sha: null,
    deleted_at: null,
    in_progress_merge_commit_sha: null,
    lock_version: 0,
    source: {
      name: 'code-review',
      description: '',
      web_url: 'http://git.mistong.com/jingweirong/code-review',
      avatar_url: null,
      git_ssh_url:
        'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
      namespace: 'jingweirong',
      visibility_level: 20,
      path_with_namespace: 'jingweirong/code-review',
      default_branch: 'master',
      homepage: 'http://git.mistong.com/jingweirong/code-review',
      url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    },
    target: {
      name: 'code-review',
      description: '',
      web_url: 'http://git.mistong.com/jingweirong/code-review',
      avatar_url: null,
      git_ssh_url:
        'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
      namespace: 'jingweirong',
      visibility_level: 20,
      path_with_namespace: 'jingweirong/code-review',
      default_branch: 'master',
      homepage: 'http://git.mistong.com/jingweirong/code-review',
      url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
      http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    },
    last_commit: {
      id: '840a5c1f2a58e83f29a168d29ab59b0f0ff45e05',
      message: 'Update README.md',
      timestamp: '2022-01-18T10:14:27+08:00',
      url: 'http://git.mistong.com/jingweirong/code-review/commit/840a5c1f2a58e83f29a168d29ab59b0f0ff45e05',
      author: { name: 'jingweirong', email: 'jingweirong@mistong.com' },
    },
    work_in_progress: false,
    url: 'http://git.mistong.com/jingweirong/code-review/merge_requests/2',
    action: 'open',
  },
  repository: {
    name: 'code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    description: '',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
  },
  assignee: {
    name: 'jingweirong',
    username: 'jingweirong',
    avatar_url: 'http://git.mistong.com/uploads/user/avatar/251/avatar.png',
  },
};
