export default {
  object_kind: 'push',
  event_name: 'push',
  before: 'a49caa1ee80b86f61a7eb25a74ba6661deb484de',
  after: 'adf4ea71d6996cf1e51b88bced9f501aa25358df',
  ref: 'refs/heads/master',
  checkout_sha: 'adf4ea71d6996cf1e51b88bced9f501aa25358df',
  message: null,
  user_id: 251,
  user_name: 'jingweirong',
  user_email: 'jingweirong@mistong.com',
  user_avatar: 'http://git.mistong.com/uploads/user/avatar/251/avatar.png',
  project_id: 2810,
  project: {
    name: 'code-review',
    description: '',
    web_url: 'http://git.mistong.com/jingweirong/code-review',
    avatar_url: null,
    git_ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    namespace: 'jingweirong',
    visibility_level: 20,
    path_with_namespace: 'jingweirong/code-review',
    default_branch: 'master',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    http_url: 'http://git.mistong.com/jingweirong/code-review.git',
  },
  commits: [
    {
      id: 'adf4ea71d6996cf1e51b88bced9f501aa25358df',
      message: 'Update README.md',
      timestamp: '2022-01-17T18:09:22+08:00',
      url: 'http://git.mistong.com/jingweirong/code-review/commit/adf4ea71d6996cf1e51b88bced9f501aa25358df',
      author: { name: 'jingweirong', email: 'jingweirong@mistong.com' },
      added: [],
      modified: ['README.md'],
      removed: [],
    },
  ],
  total_commits_count: 1,
  repository: {
    name: 'code-review',
    url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    description: '',
    homepage: 'http://git.mistong.com/jingweirong/code-review',
    git_http_url: 'http://git.mistong.com/jingweirong/code-review.git',
    git_ssh_url: 'ssh://git@git.mistong.com:10022/jingweirong/code-review.git',
    visibility_level: 20,
  },
};
